Feature 7: Pagination
sad-wtag/ToDoApp_VanillaJS pull request #10
Opened 2024-07-14 10:45 UTC by saa-wtag

[[Bonus] Task 8: Pagination](https://trello.com/c/B8XnBy4w)
This PR introduces the functionality of pagination the todos by clicking the Load more button at bottom.

**Functionalities:**
- By clicking load more button next tasks will be shown on the page upto next 9 or less (if next tasks no is less than 9) tasks.

Please have a close look on this PR and kindly put your valuable comments.

https://github.com/saa-wtag/ToDoApp_VanillaJS/assets/164306406/b339aa5d-b436-4edd-96eb-f7850fa4d464

2024-07-16 10:48 UTC, sal-wtag approved these changes

2024-07-25 05:13 UTC, maa-wtag reviewed
please resolve the PR conflicts first

2024-07-26 08:51 UTC, saa-wtag commented
> please resolve the PR conflicts first

Done, bhai.

2024-07-26 09:19 UTC, maa-wtag commented on styles.css
> +  margin-top: 0.4%;
could we use a proper value instead

2024-07-26 09:32 UTC, maa-wtag requested changes

2024-07-26 09:32 UTC, maa-wtag commented on js/script.js
>  const filteredSearchableTasksOrTasks = filteredOrSearchableTasks.length
```suggestion
const finalTaskList = filteredOrSearchableTasks.length
```

2024-07-26 09:32 UTC, maa-wtag commented on js/script.js
> +
```suggestion
$loadMore.addEventListener("click", () => {
  if (!Array.isArray(tasks) || !Array.isArray(filteredOrSearchableTasks)) {
    console.error("Task arrays are not defined correctly.");
    return;
  }

  tasksDisplayed = Math.min(
    tasksDisplayed + TASK_PER_PAGE,
    filteredOrSearchableTasks.length || tasks.length
  );

  if (typeof renderTasks !== 'function') {
    console.error("renderTasks is not a function");
    return;
  }

  renderTasks(finalTaskList);
});

```

2024-07-26 09:38 UTC, saa-wtag commented on js/script.js
> +
Done, bhai.

2024-07-26 09:38 UTC, saa-wtag commented on js/script.js
>  const filteredSearchableTasksOrTasks = filteredOrSearchableTasks.length
Done, bhai.

2024-07-26 09:38 UTC, saa-wtag commented on styles.css
> +  margin-top: 0.4%;
Done, bhai

2024-07-26 09:44 UTC, maa-wtag requested changes

2024-07-26 09:44 UTC, maa-wtag commented on js/script.js
> +  if (!Array.isArray(tasks) || !Array.isArray(finalTaskList)) {
```suggestion
  if (!Array.isArray(tasks) || !Array.isArray(filteredOrSearchableTasks)) {
```

2024-07-26 09:44 UTC, maa-wtag commented on js/script.js
> +    finalTaskList.length || tasks.length
```suggestion
    filteredOrSearchableTasks.length || tasks.length
```

2024-07-26 09:59 UTC, maa-wtag approved these changes

2024-07-28 07:43 UTC, hhu-wtag approved these changes

2024-07-28 07:45 UTC, merged